FROM python:3.10-slim
WORKDIR /app
COPY trainer/trainer.py .
RUN pip install pandas scikit-learn joblib
CMD ["python", "trainer.py"]
FROM python:3.10-slim
WORKDIR /app
COPY trainer.py ./
RUN pip install --no-cache-dir pandas scikit-learn joblib minio
RUN mkdir -p /app/model
CMD ["python", "trainer.py"]
