apiVersion: v1
kind: Service
metadata:
  name: minio-ui
  namespace: default
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: web-ui
      port: 9001
      targetPort: 9001
      nodePort: 30911   
