apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serving-api
  template:
    metadata:
      labels:
        app: serving-api
    spec:
      containers:
        - name: serving-container
          image: ylou25/serving-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          command: ["uvicorn"]
          args: ["app:app", "--host", "0.0.0.0", "--port", "8000"]

---
apiVersion: v1
kind: Service
metadata:
  name: serving-service
spec:
  type: NodePort
  selector:
    app: serving-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30800
