apiVersion: batch/v1
kind: Job
metadata:
  name: trainer-job
spec:
  template:
    spec:
      containers:
      - name: trainer
        image: ylou25/trainer-job:latest  
        env:
        - name: MINIO_ENDPOINT
          value: "minio:9000"
      restartPolicy: Never
