name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'serving/**'
      - 'ui/**'
      - '.github/workflows/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    env:
      DO_DEPLOY: ${{ secrets.KUBE_CONFIG_DATA != '' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies & tools
        run: |
          pip install -r serving/requirements.txt
          pip install -r ui/requirements.txt
          pip install pytest flake8 black

      - name: Lint code
        run: flake8 serving ui

      - name: Check formatting
        run: black --check serving ui

      - name: Run backend tests
        run: pytest serving/tests

      - name: Run frontend tests
        run: pytest ui/tests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push serving-api
        uses: docker/build-push-action@v5
        with:
          context: serving
          file: serving/Dockerfile
          push: true
          tags: |
            ylou25/serving-api:latest
            ylou25/serving-api:${{ github.sha }}

      - name: Build & push streamlit-ui
        uses: docker/build-push-action@v5
        with:
          context: ui
          file: ui/Dockerfile
          push: true
          tags: |
            ylou25/streamlit-ui:latest
            ylou25/streamlit-ui:${{ github.sha }}

      # ---------------- 部署（当且仅当你配置了 KUBE_CONFIG_DATA） ----------------
      - name: Configure kubectl
        if: env.DO_DEPLOY == 'true'
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Write kubeconfig
        if: env.DO_DEPLOY == 'true'
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Deploy serving-api
        if: env.DO_DEPLOY == 'true'
        run: |
          kubectl set image deployment/serving-api serving-container=ylou25/serving-api:latest
          kubectl rollout status deployment/serving-api

      - name: Deploy streamlit-ui
        if: env.DO_DEPLOY == 'true'
        run: |
          kubectl set image deployment/streamlit-ui streamlit-container=ylou25/streamlit-ui:latest
          kubectl rollout status deployment/streamlit-ui
